pipeline:
  clone:
    image: plugins/git
    when:
      event:
        exclude: [deployment]
        include: [push]
  test:
    group: A
    image: razorpay/onggi:php-7.1-nginx
    pull: true
    secrets: [docker_username, docker_password, git_token]
    environment:
      - DB_HOST=db-auth
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=auth_test
    commands:
      - ./dockerconf/run_drone_tests.sh
    when:
      event:
        exclude: [deployment]
        include: [push]
  build:
    group: A
    image: plugins/docker
    repo: razorpay/auth
    secrets: [docker_username, docker_password, git_token]
    build_args_from_env: [git_token]
    build_args:
     - GIT_COMMIT_HASH=${DRONE_COMMIT_SHA}
    tags: ${DRONE_COMMIT_SHA}
    when:
      status: [success]
      event:
        exclude: [deployment]
        include: [push]
  build-notify:
    image: plugins/slack
    secrets: [slack_webhook]
    channel: tech_distelli
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      {{#success build.status}}
        Build succeeded.
      {{else}}
        Build failed.
      {{/success}}
        Build No:{{build.number}}
        Branch: {{build.branch}}
        Commit: {{build.commit}}
        Author: {{build.author}}
        Started at: {{build.started}}
        Time taken: {{since build.started}}
        Link: {{build.link}}
    when:
      event:
        exclude: [deployment]
        include: [push]
services:
  db-auth:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_test
    when:
      event:
        exclude: [deployment]
        include: [push]
pipeline:
  deploy-stage:
    image: razorpay/drone-kubernetes:latest
    pull: true
    secrets:
      - docker_username
      - docker_password
      - server_url_stage
      - server_cert_stage
      - client_cert_stage
      - client_key_stage
    user: drone
    cluster: stage
    auth_mode: client-cert
    deployment: auth
    repo: razorpay/auth
    container: auth
    namespace: auth
    tag:
      - ${DRONE_COMMIT_SHA}
    when:
      environment: stage
      event:
        exclude: [push]
        include: [deployment]
  deploy-prod-blue:
    group: PROD_DEPLOY
    image: razorpay/drone-kubernetes:latest
    pull: true
    secrets:
      - docker_username
      - docker_password
      - server_url_prodblue
      - server_cert_prodblue
      - client_cert_prodblue
      - client_key_prodblue
    user: drone
    cluster: prod-blue
    auth_mode: client-cert
    deployment: auth
    repo: razorpay/auth
    container: auth
    namespace: auth
    tag:
      - ${DRONE_COMMIT_SHA}
    when:
      environment: prod
      event:
        exclude: [push]
        include: [deployment]
      branch: master
  deploy-prod-green:
    group: PROD_DEPLOY
    image: razorpay/drone-kubernetes:latest
    pull: true
    secrets:
      - docker_username
      - docker_password
      - server_url_prodgreen
      - server_cert_prodgreen
      - client_cert_prodgreen
      - client_key_prodgreen
    user: drone
    cluster: prod-green
    auth_mode: client-cert
    deployment: auth
    repo: razorpay/auth
    container: auth
    namespace: auth
    tag:
      - ${DRONE_COMMIT_SHA}
    when:
      environment: prod
      event:
        exclude: [push]
        include: [deployment]
      branch: master
