version: '2'
services:

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 14268:14268
  auth:
    stop_signal: SIGQUIT
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - GIT_TOKEN
    image: razorpay:auth
    container_name: razorpay-auth
    volumes:
      - .:/app
    links:
      - db-auth
      - jaeger
    depends_on:
      - db-auth
    ports:
      - 28095:8888
    environment:
      DB_HOST: db-auth
      DB_DATABASE: auth
      DB_USERNAME: auth
      DB_PASSWORD: 123
      APP_CONTEXT: dev
      APP_MODE: dev
      GIT_COMMIT_HASH: dev-commit
      NODE_NAME: jaeger
      JAEGER_HOSTNAME: jaeger
      JAEGER_PORT: 6831
  db-auth:
    image: mysql:5.7
    ports:
      - 23309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: 123
  signer-cache:
    image: redis:6-alpine
    ports:
      - 26379:6379
    container_name: signer-cache
