FROM c.rzp.io/razorpay/containers:base-nginx-php7

ARG GIT_TOKEN
ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}

VOLUME ['/app']

COPY ./dockerconf/entrypoint.sh /entrypoint.sh

WORKDIR /app

RUN chown -R nginx.nginx /app

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
