version: '2'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - GIT_TOKEN
    image: razorpay:auth
    container_name: razorpay-auth
    networks:
      - api_default
    volumes:
      - .:/app
    links:
      - db-auth
    depends_on:
      - db-auth
    ports:
      - 28095:8888
    environment:
      DB_HOST: db-auth
      DB_DATABASE: auth
      DB_USERNAME: auth
      DB_PASSWORD: 123
      APP_CONTEXT: dev
      APP_MODE: dev
      GIT_COMMIT_HASH: dev-commit
  db-auth:
    image: mysql:5.7
    networks:
      - api_default
    ports:
      - 23309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: auth
      MYSQL_USER: auth
      MYSQL_PASSWORD: 123
networks:
  api_default:
    external: true
