FROM razorpay/containers:base-nginx-php7

ARG GIT_TOKEN
ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}

VOLUME ['/app']

RUN chown -R nginx.nginx /app

COPY ./dockerconf/boot.sh /boot.sh

WORKDIR /app

EXPOSE 80

ENTRYPOINT ["/boot.sh"]
