version: '2'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: razorpay:auth
    volumes:
      - .:/app
    links:
      - db-auth
    depends_on:
      - auth_db
    ports:
      - 28095:80
    environment:
      DB_HOST: db-auth
      DB_DATABASE: auth
      DB_USERNAME: auth
      DB_PASSWORD: 123
      APP_CONTEXT: dev
  db-auth:
      image: mysql:5.6
      ports:
        - 23309:3306
      environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_DATABASE: auth
        MYSQL_USER: auth
        MYSQL_PASSWORD: 123
