apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: auth
  name: auth
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      name: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: iam-stage-auth
      labels:
        name: auth
    spec:
      containers:
      - env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: gimli
              key: APP_MODE
        image: razorpay/auth:c8e3db37804b9919922e2d6459548c0ee92b01fb
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        readinessProbe:
          httpGet:
            path: /status
            port: 80
            httpHeaders:
              - name: Host
                value: stage-auth.razorpay.com
          initialDelaySeconds: 60
          periodSeconds: 120
        livenessProbe:
          httpGet:
            path: /commit.txt
            port: 80
            httpHeaders:
              - name: Host
                value: stage-auth.razorpay.com
          initialDelaySeconds: 60
          periodSeconds: 20
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
      terminationGracePeriodSeconds: 60
      volumes:
      - name: trace
        hostPath:
          path: /var/log/fluentd/gimli/trace
      - name: nginx
        hostPath:
          path: /var/log/fluentd/gimli/nginx
      imagePullSecrets:
      - name: registry
      nodeSelector:
        node-role.kubernetes.io/node-components: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
