<?php

namespace Unit\Service\Kafka;

use App\Services\Kafka\KafkaTrait;
use App\Tests\Unit\UnitTestCase;

class kafkaTraitTest extends UnitTestCase
{
    public function setUp(): void
    {
        parent::setUp();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function callMethod($obj, $name, array $args)
    {
        $class = new \ReflectionClass($obj);
        $method = $class->getMethod($name);
        $method->setAccessible(true);
        return $method->invokeArgs($obj, $args);
    }

    /**
     * @Test
     * testProduceTraitGetConfig should create config map for kafka producer.
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     * @return void
     */
    public function testProduceTraitGetConfig()
    {
        putenv('QUEUE_KAFKA_CONSUMER_BROKERS=some_value');
        putenv('QUEUE_KAFKA_CONSUMER_TLS_ENABLED=true');
        $trait = $this->getObjectForTrait(KafkaTrait::class);
        $conf = $this->callMethod(
            $trait,
            'getConfig',
            array()
        )->dump();

        $this->assertEquals($conf['client.id'], 'auth-kafka');
        $this->assertEquals($conf['enable.ssl.certificate.verification'], 'true');
        $this->assertEquals($conf['security.protocol'], 'ssl');
        $this->assertEquals($conf['enable.auto.commit'], 'false');
    }

    //TODO add more test cases after Refactoring.
}
