name: CI
on: [push]
jobs:
  cancel:
    runs-on: [self-hosted]
    name: Cancel Previous Runs
    if: always()
    steps:
      - uses: styfle/cancel-workflow-action@d57d93c3a8110b00c3a2c0b64b8516013c9fd4c9
        if: ${{ github.ref != 'refs/heads/master' }}
        name: cancel old workflows
        id: cancel
        with:
          access_token: ${{ github.token }}
      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"
  build:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    continue-on-error: false
    name: Build Image
    steps:
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: "auth-service,opencensus-php,config-proto,dcs-php-sdk,metrics-php,trace,spine,oauth,outbox-php,opencensus-php-exporter-jaeger"
      - name: checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          context: .
          secrets: |
            git_token=${{ steps.app-token.outputs.token }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            GIT_USERNAME=rzp
          push: true
          tags: c.rzp.io/${{ github.repository }}:${{ github.sha }}
  run_test:
    name: Test Suite
    runs-on: [ self-hosted, non-api ]
    needs: [ cancel ]
    continue-on-error: false
    container:
      image: harbor.razorpay.com/razorpay/onggi:php-8.1-nginx
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    steps:
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: "auth-service,opencensus-php,config-proto,dcs-php-sdk,metrics-php,trace,spine,oauth,outbox-php,opencensus-php-exporter-jaeger,edge,credcase,authz,outbox-relay,terraform-kong,mock-gateway"
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Running tests
        id: running_test
        run: |
          /bin/sh ./ci-assets/run_unit_tests.sh
        env:
          DB_HOST: db-auth
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DATABASE: auth
          SIGNER_CACHE_HOST: signer-cache
          SIGNER_CACHE_PORT: 6379
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
          BRANCH: ${{ github.ref }}
      - name: Set Sonarqube Project
        id: set_sonar_project
        run: |
          SONAR_PROJECT="AuthServiceDevCoverageCheck"
          BRANCH=${{ github.ref }}
          if [[ "$BRANCH" == "refs/heads/master" ]]; then
          SONAR_PROJECT="AuthService";
          fi
          echo ::set-output name=sonar_project::$SONAR_PROJECT
          echo "Sonar Project : $SONAR_PROJECT for branch : $BRANCH"
      - name: Integration Coverage Push to sonar
        uses: sonarsource/sonarcloud-github-action@v1.4
        env:
          SONAR_HOST: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARCLOUD_URL: https://sonar.razorpay.com
          SONAR_INTEGRATION_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        with:
          projectBaseDir: /github/workspace/app/
          args: >
            -Dsonar.host.url=https://sonar.razorpay.com
            -Dsonar.projectKey=${{ steps.set_sonar_project.outputs.sonar_project }}
            -Dsonar.projectName=${{ steps.set_sonar_project.outputs.sonar_project }}
            -Dsonar.projectVersion=${{ github.sha }}
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.php.coverage.reportPaths=/github/workspace/clover.xml
            -Dsonar.exclusions=tests/**,vendor,storage/**,Exception/**,Services/Mock/**
      - name: Find PR Number
        if: github.ref != 'refs/heads/master'
        uses: razorpay/gh-find-current-pr@v1
        id: findPr
      - name: check values
        run: echo ${{ github.ref }}::${{ steps.findPr.outputs.number }}
      - name: Code Quality Analysis
        if: github.ref != 'refs/heads/master' && success() && steps.findPr.outputs.number
        id: code_quality_analysis
        uses: docker://razorpay/onggi:nginx
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          entrypoint: /bin/bash
          args: ci-assets/quality_analysis.sh
        env:
          SONAR_HOST: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GIT_SHA: ${{ github.sha }}
      - name: Add Quality Report Comment
        if: github.ref != 'refs/heads/master' && success() && steps.findPr.outputs.number
        uses: razorpay/create-comment@v1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          check-only-first-line: true
          unique: true
          number: ${{ steps.findPr.outputs.pr }}
          comment: |
            ${{ steps.code_quality_analysis.outputs.quality_report }}
      - name: Check If PR is hotfix or revert
        if: contains(github.ref, 'hotfix') || contains(github.ref, 'revert')
        id: is_pr_hotfix_or_revert
        run: echo "::set-output name=flag::true"
      - name: TestCoverage OK
        if: steps.is_pr_hotfix_or_revert.outputs.flag != 'true' && steps.code_quality_analysis.outputs.is_test_coverage_ok == 'true'
        run: |
          echo "Test Coverage is OK"
          exit 0
      - name: TestCoverage Less
        if: steps.is_pr_hotfix_or_revert.outputs.flag != 'true' && steps.code_quality_analysis.outputs.is_test_coverage_ok == 'false'
        run: |
          echo "Test Coverage failed. Try adding test cases"
          exit 1
    services:
      db-auth:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: auth
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      signer-cache:
        image: redis:6-alpine
        ports:
          - 6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  slack-notify:
    runs-on: [ self-hosted ]
    name: Build Notify
    needs: [ run_test, build ]
    steps:
      - name: Sending build success notification (Slack)
        if: needs.run_test.result == 'success' && needs.build.result == 'success'
        env:
          SLACK_MESSAGE: 'Build success.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Actions # Optional. (defaults to webhook app)
          SLACK_CHANNEL: tech_distelli # Optional. (defaults to webhook)
          SLACK_ICON: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4 # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: rtCamp/action-slack-notify@ca2febb266f78a54a245d815081549c522099b76
      - name: Sending build failed notification (Slack)
        if: needs.run_test.result != 'success' || needs.build.result != 'success'
        env:
          SLACK_MESSAGE: 'Build failed.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#8B0000'
          SLACK_USERNAME: Github Actions # Optional. (defaults to webhook app)
          SLACK_CHANNEL: tech_distelli # Optional. (defaults to webhook)
          SLACK_ICON: https://avatars3.githubusercontent.com/u/9919?s=40&v=4 # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
        uses: rtCamp/action-slack-notify@ca2febb266f78a54a245d815081549c522099b76
  edge-e2e-test-webhook:
    name: Edge E2E test webhook
    runs-on: [ self-hosted ]
    needs: [ build ]
    steps:
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: "auth-service,opencensus-php,config-proto,dcs-php-sdk,metrics-php,trace,spine,oauth,outbox-php,opencensus-php-exporter-jaeger,edge,credcase,authz,outbox-relay,terraform-kong,mock-gateway"
      - uses: actions/checkout@v2
      - name: Find current pr
        uses: jwalton/gh-find-current-pr@v1.3.0
        id: findPr
      - name: Triggers argo workflows webhook to execute e2e tests
        if: steps.findPr.outputs.number || github.ref == 'refs/heads/master'
        env:
          SPINNAKER_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          GITHUB_TOKEN: '${{ steps.app-token.outputs.token }}'
          EDGE_PIPELINE_ID: "deployment-v2"
        run: >
          ./.github/scripts/run-edge-e2e.sh ${{ github.sha }} ${{ secrets.ARGO_TOKEN }}
  workflow_status:
    runs-on: [ self-hosted ]
    name: Update Status Check
    needs: [ build, run_test, edge-e2e-test-webhook ]
    if: always()
    steps:
      - name: Failed
        id: failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo 'Failing the workflow for github status check.'
          exit 1
      - name: Success
        if: steps.failed.conclusion == 'skipped'
        run: |
          echo 'Status check has passed!'
          exit 0
