name: Combined Status Check

on:
  workflow_run:
    workflows: [CI]
    branches-ignore: [master]
    types:
      - completed

jobs:
  check_workflow_status:
    runs-on: [ self-hosted ]
    name: Check workflow status
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: |
            touch apis.json
            echo 'Pull pr workflow statuses'
            curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  -H "Authorization: token ${{ github.token }}" -o apis.json \
            https://api.github.com/repos/${{ github.repository }}/actions/runs?head_sha=${{ github.event.workflow_run.head_sha }}
            failed_workflows=$(cat apis.json | jq '.workflow_runs | .[] | select(.name == ("CI")) | select(.conclusion != "success") | .name')
            echo "Failed workflows ${failed_workflows}"

            if [[ $failed_workflows ]]
            then
              echo "Found failed workflow, to block this PR merge updating combined status check workflow state to 'failure'"
              curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
              -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }}
              exit 1
            else
              echo "Not found any failed workflow, to allow this PR merge updating combined status check workflow state to 'success'"
              curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
              -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }}
              exit 0
            fi
