name: Verified E2E Build Trigger

on: deployment

env:
  IMAGE_TAG: ${{ github.event.deployment.payload.image_tag }}

jobs:

  # Job to print the commit ID and Image Tag
  print-commit-id:
    name: Print Commit ID and Image Tag
    runs-on: [ self-hosted ]
    steps:
      - name: Triggered Commit ID and Image Tag
        run: |
          echo "Commit ID: ${{ github.sha }}"
          echo "Image Tag: ${{ env.IMAGE_TAG }}"

  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ARM64
          - X64
    if: github.event.deployment.environment == 'e2e' # Run only if environment is e2e
    runs-on:
      - k8s-runner
      - non-api
      - ${{ matrix.platform }}
    steps:
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: "auth-service,opencensus-php,config-proto,dcs-php-sdk,metrics-php,trace,spine,oauth,outbox-php,opencensus-php-exporter-jaeger"
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: matrixLowercase
        run: echo "::set-output name=platform::${UPPERCASE_MATRIX_PLATFORM,,}"
        env:
          UPPERCASE_MATRIX_PLATFORM: ${{ matrix.platform }}
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$platform" # This will output 'yellow'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          secrets: |
            git_token=${{ steps.app-token.outputs.token }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            GIT_USERNAME=rzp
          push: true
          tags: c.rzp.io/${{ github.repository }}:${{ env.IMAGE_TAG }}-${{ steps.matrixLowercase.outputs.platform }}

  build-multi-architecture:
    needs:
      - build
    runs-on:
      - k8s-runner
      - non-api
      - ARM64
    if: github.event.deployment.environment == 'e2e'
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: c.rzp.io/razorpay/edge-dp
          flavor: suffix=-${{ github.sha }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: c.rzp.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
          suffixes: |
            -arm64
            -x64
