name: Test Suite
on: [push]

jobs:
  test:
    runs-on: [ self-hosted, non-api ]
    services:
      jaeger-all-in-one:
        image: jaegertracing/all-in-one:latest
        ports:
          - 16686:16686

    steps:
      - name: Checkout to code repo
        uses: actions/checkout@v2

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug

      - name: Update dependencies in lock file
        run: composer update

      - name: Install dependencies
        run: composer install

      - name: Run unit tests
        continue-on-error: true
        run: vendor/bin/phpunit tests/

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
            files: build/clover.xml
            verbose: true
