name: Test Suite
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout to code repo
        uses: actions/checkout@v2

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug

      - name: Update dependencies in lock file
        run: composer update

      - name: Install dependencies
        run: composer install

      - name: Run Jaeger all in one Docker
        uses: addnab/docker-run-action@v3
        with:
          image: jaegertracing/all-in-one:latest
          run: |
            docker run -d -p6831:6831/udp -p16686:16686 --name=jaeger-server jaegertracing/all-in-one:latest &

      - name: Run unit tests
        continue-on-error: true
        run: vendor/bin/phpunit tests/

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
            files: build/clover.xml
            verbose: true
